H.cpp
hxzwww/sem_cpp pull request #11
Opened 2021-11-18 20:57 UTC by hxzwww

https://codeforces.com/group/PVbQ8eK2T4/contest/347382/submission/136108797

2021-11-21 20:36 UTC, ylyubimov requested changes

2021-11-21 20:36 UTC, ylyubimov commented on H.cpp
> +void lsdSort(unsigned long long* array, int size, unsigned long long* answer) {
Давай вспомогательный массив внутри создать. Т.е. хочу LsdSort(array, size)l;

2021-11-21 20:36 UTC, ylyubimov commented on H.cpp
> +    len = 256
зачем через enum?
Почему не просто const int LEN = 256;?

2021-11-21 20:36 UTC, ylyubimov commented on H.cpp
> +    return (num >> (8 * (part - 1))) % len;
8 c 256 не связано?)

2021-11-22 00:45 UTC, hxzwww commented
https://codeforces.com/group/PVbQ8eK2T4/contest/347382/submission/136374294

2021-12-11 12:35 UTC, closed without merging