1 b
hxzwww/sem_cpp pull request #22
Opened 2022-03-08 20:54 UTC by hxzwww

https://codeforces.com/group/PVbQ8eK2T4/contest/368711/submission/148928263

2022-04-24 21:11 UTC, DmitryKorepanov requested changes

2022-04-24 21:11 UTC, DmitryKorepanov commented on B.cpp
> +    vector<int> dp_by_val(n, -1e9);
Решение должно быть вне main: вызвали метод, получили sequence, вывели ответ.

2022-04-24 21:11 UTC, DmitryKorepanov commented on B.cpp
> +    vector<int> dp_by_ind(n);
Нужно приложить стандартное описание динамики:
- что храним в dp
- как пересчитываем
- где ответ

2022-04-26 21:53 UTC, hxzwww commented on B.cpp
> +    vector<int> dp_by_val(n, -1e9);
https://codeforces.com/group/PVbQ8eK2T4/contest/368711/submission/155073025

2022-05-23 07:14 UTC, DmitryKorepanov approved these changes

2022-05-23 07:16 UTC, closed without merging