D.cpp
hxzwww/sem_cpp pull request #9
Opened 2021-11-18 20:38 UTC by hxzwww

2021-11-18 20:41 UTC, hxzwww commented
https://codeforces.com/group/PVbQ8eK2T4/contest/347382/submission/135492019

2021-11-21 20:47 UTC, ylyubimov requested changes

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +            heapSize = 32;
список инициализации

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +        int pointerSize;
чем curPointerSize отличается от pointerSize? По названию совсем не понятно. Лучше bufferSize писать или как-то так

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +            *this = other;
тоже список инициализации

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +            if (this == &other) {
в операторе равно не гарантируется, что объект пустой, поэтому надо старые буферы почистить

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +        void exchange(int u, int v) {
Вот это не public интерфейс

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +                else break;
Можно перепистаь в один while судя по всему
while(v > 1 && heap[v] < heap[v / 2]) { exchange(.... }

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +                if (2 * v + 1 <= curHeapSize && heap[2 * v + 1] < heap[2 * v]) {
можно везде 2 * v на u заменить

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +                else break;
можно else не писать)

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +            heapSize = std::min(heapSize * 2, 1000000);
зачем ограничение сверху?

2021-11-21 20:47 UTC, ylyubimov commented on D.cpp
> +        }
А нельзя метод переаллокации сделать общий и вызвать для каждого массива?

2021-11-22 13:31 UTC, hxzwww commented on D.cpp
> +                else break;
нельзя, там нет смысла дальше спускаться, тем более будет TL

2021-11-22 13:32 UTC, hxzwww commented on D.cpp
> +        }
неудобно по-моему, один массив long, а второй int

2021-11-22 13:34 UTC, hxzwww commented on D.cpp
> +            heapSize = std::min(heapSize * 2, 1000000);
ну нам не нужно более 10^6 элементов, зачем память лишнюю выделять

2021-12-11 12:33 UTC, closed without merging